spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      no delete table
#      ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#       recommend 100 ~ 1000, it is to make In Query, almost default option
        default_batch_fetch_size: 10
logging:
  level:
    org.hibernate.SQL: debug
#    explain parameter
#    org.hibernate.orm.jdbc.bind: trace
