drop table if exists member cascade;
create table member
(
    id bigint generated by default as identity, -- 값 지정 안해도 자동 생성
    name varchar(255),
    primary key (id)
);

insert into member(name) values();

truncate table member;